### ISSUE TITLE
关于playwright应用于打包后的electron应用

### ISSUE THREAD

**Issue by noob000** [tanshuai/electron-playwright-e2e-test-quick-start#2]
您好，我在spectron的issue看到了您的这个仓库，我想请问您，有尝试过利用playwright对打包后的electron应用进行自动化测试吗，我看到您这个是针对开发模式下的electron应用进行测试

**Comment by tanshuai** [comment]
Playwright 针对打包后的Electron应用进行测试，你可以参考我的一个开源产品项目：[alphabiz](https://github.com/tanshuai/alphabiz)，在其中的package.json test/ .github/workflows中有关于electron打包后的playwright的测试用例。如果是Windows模式下，建议用appnium再做一遍生产模式下的测试。

**Comment by noob000** [comment]
十分感谢您的回复！

**Comment by noob000** [comment]
> Playwright 针对打包后的Electron应用进行测试，你可以参考我的一个开源产品项目：[alphabiz](https://github.com/tanshuai/alphabiz)，在其中的package.json test/ .github/workflows中有关于electron打包后的playwright的测试用例。如果是Windows模式下，建议用appnium再做一遍生产模式下的测试。

十分感谢您的回复！
